version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  webpack:
    build:
      context: .
      dockerfile: Dockerfile.webpack
    command: yarn run dev --disable-host-check true --host 0.0.0.0
    ports:
      - "3035"
    volumes:
      - ./webpack:/app/webpack
  web:
    build: .
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpack
