version: 2
jobs:
  build:
    working_directory: ~/lesleh.co.uk3
    
    # Primary container image where all commands run
    
    docker:
      - image: circleci/ruby:2.6.1-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
    
    # Service container image available at `host: localhost`
    
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: lesleh_co_uk3_test
        
    steps:
      - checkout

      # Restore bundle cache
      - restore_cache:
          keys:
            - lesleh.co.uk3-{{ checksum "Gemfile.lock" }}
            - lesleh.co.uk3-

      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - run: sudo apt install -y postgresql-client || true

      # Store bundle cache
      - save_cache:
          key: lesleh.co.uk3-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load

      - run:
          name: Parallel RSpec
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o /tmp/test-results/rspec.xml

      # Save artifacts
      - store_test_results:
          path: /tmp/test-results
